# Generated by Django 2.2.11 on 2020-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('AD', 'Administrador'), ('GE', 'Gerente'), ('OP', 'Operador'), ('CL', 'Cliente')], default='', max_length=2),
        ),
    ]
