# Generated by Django 3.0.5 on 2020-05-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('CO', 'Corporativo'), ('NA', 'Natural')], default='', max_length=2)),
            ],
        ),
    ]
