# Generated by Django 2.2.11 on 2020-05-16 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Cliente')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.ElectricMeter')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateGenerated', models.DateField(auto_now=True)),
                ('dateExpiry', models.DateField()),
                ('amount', models.FloatField()),
                ('totalConsumed', models.IntegerField()),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumo.Consumo')),
            ],
        ),
    ]
