# Generated by Django 2.2.11 on 2020-05-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='meter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.ElectricMeter'),
        ),
    ]
